name: Run tests with Tox

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-unit-wheelhouse:
    name: Lint, Unit, Wheelhouse
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        pip install tox
        sudo snap install charm --classic
    - name: Lint
      run: tox -vve lint
    - name: Unit Tests
      run: tox -vve unit
    - name: Validate Wheelhouse
      run: tox -vve validate-wheelhouse
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@master
        with:
          provider: lxd
      - name: Install Docker
        run: |
          sudo apt install -qyf docker.io
          sudo chmod 0666 /var/run/docker.sock
      - name: Run test
        run: tox -e integration
