name: Run tests with Tox

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-inclusive-naming-check:
    name: Inclusive Naming
    uses: canonical-web-and-design/Inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"

  lint-unit:
    name: Lint Unit
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@main

  validate-wheelhouse:
    uses: charmed-kubernetes/workflows/.github/workflows/validate-wheelhouse.yaml@main  

  integration-test:
    name: Integration test with VMWare
    runs-on: self-hosted
    needs:
      - call-inclusive-naming-check
      - lint-unit
      - validate-wheelhouse
    timeout-minutes: 360
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: vsphere
          credentials-yaml: ${{ secrets.CREDENTIALS_YAML }}
          clouds-yaml: ${{ secrets.CLOUDS_YAML }}
          bootstrap-options: "--model-default datastore=vsanDatastore --model-default primary-network=VLAN_2764"
      - name: Install docker (flannel resources)
        run: sudo snap install docker
      - name: Install juju-crashdump
        run: sudo snap install juju-crashdump --classic
      - name: Run test
        run: tox -e integration
      - name: Upload crashdump
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: crashdump
          path: juju-crashdump-*.tar.xz
